include:
  - /authentication/.gitlab-ci.yml
  - /database/.gitlab-ci.yml
  - /viewer/.gitlab-ci.yml
  - /schedule-edit/.gitlab-ci.yml
  - /schedule-generate/.gitlab-ci.yml
  - /nl.tudelft.unischeduler.rules.rules/.gitlab-ci.yml