server:
  port: 8100

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url: http://localhost:8761/eureka
#  instance:
#    hostname: localhost

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    authentication-service:
      path: /authentication/**
      serviceId: gateway-authentication-service
      stripPrefix: true
  ignored-services: '*'