image: gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

database-build:
  stage: build
  script:
    gradle --build-cache :database:assemble

database-checkStyle:
  stage: staticAnalysis
  script:
    gradle :database:checkstyleMain :database:checkStyleTest

database-PMD:
  stage: staticAnalysis
  script:
    gradle :database:pmdMain :database:pmdTest

database-test:
  stage: test
  script:
    gradle :database:test
