INSERT INTO app_user
VALUES ('a.baran@student.tudelft.nl', 'pass1');
INSERT INTO app_user
VALUES ('a.kuba@student.tudelft.nl', 'pass2');
INSERT INTO app_user
VALUES ('a.mert@student.tudelft.nl', 'pass3');
INSERT INTO app_user
VALUES ('a.nathan@student.tudelft.nl', 'pass4');
INSERT INTO app_user
VALUES ('a.jop@student.tudelft.nl', 'pass5');
INSERT INTO app_user
VALUES ('a.louis@student.tudelft.nl', 'pass6');
INSERT INTO app_user
VALUES ('teacher@tudelft.nl', 'pass7');
INSERT INTO app_user
VALUES ('sanders@tudelft.nl', 'pass8');
INSERT INTO app_user
VALUES ('anotherteacher@tudelft.nl', 'pass9');
INSERT INTO app_user
VALUES ('faculty@tudelft.nl', 'pass10');
