package nl.tudelft.unischeduler.database.classroom;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;

@Entity
@Data
@AllArgsConstructor
@Table(name = "classroom", schema = "schedulingDB")
public class Classroom {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "full_capacity", nullable = false)
    private int fullCapacity;
    @Column(name = "name", nullable = false, unique = true)
    private String name;
    @Column(name = "building_name", nullable = false)
    private String buildingName;
    @Column(name = "floor", nullable = false)
    private int floor;

    /**
     * This method initialises the classroom object.
     */
    public Classroom() {

    }

    /**
     * This method initialises the userCourse object with specified parameters, Id is autogenerated.
     *
     * @param fullCapacity full capacity of a classroom
     * @param name name of it
     * @param buildingName building its in
     * @param floor floor it is on
     */
    public Classroom(int fullCapacity, String name, String buildingName, int floor) {
        this.fullCapacity = fullCapacity;
        this.name = name;
        this.buildingName = buildingName;
        this.floor = floor;
    }
}
