image: gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

build:
  stage: build
  script:
    gradle --build-cache :viewer:assemble

viewer-checkStyle:
  stage: staticAnalysis
  script:
    gradle :viewer:checkstyleMain :viewer:checkStyleTest

viewer-PMD:
  stage: staticAnalysis
  script:
    gradle :viewer:pmdMain :viewer:pmdTest

viewer-test:
  stage: test
  script:
    gradle :viewer:test
