image: gradle:6.7-jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  -
variables:
  MODULE_NAME: schedule-edit

stages:
  - build
  - staticAnalysis
  - test

schedule-edit-build:
  stage: build
  script:
    gradle --build-cache :schedule-edit:assemble

schedule-edit-checkStyle:
  stage: staticAnalysis
  script:
    gradle :schedule-edit:checkstyleMain :schedule-edit:checkStyleTest

schedule-edit-PMD:
  stage: staticAnalysis
  script:
    gradle :schedule-edit:pmdMain :schedule-edit:pmdTest

schedule-edit-test:
  stage: test
  script:
    gradle :schedule-edit:test
