image: gradle:6.7-jdk11

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - staticAnalysis
  - test

rules-build:
  stage: build
  script:
    gradle --build-cache :nl.tudelft.unischeduler.rules.rules:assemble

rules-checkStyle:
  stage: staticAnalysis
  script:
    gradle :nl.tudelft.unischeduler.rules.rules:checkstyleMain :nl.tudelft.unischeduler.rules.rules:checkStyleTest

rules-PMD:
  stage: staticAnalysis
  script:
    gradle :nl.tudelft.unischeduler.rules.rules:pmdMain :nl.tudelft.unischeduler.rules.rules:pmdTest

rules-test:
  stage: test
  script:
    gradle :nl.tudelft.unischeduler.rules.rules:test
